owner: ATOR-Development
repo: ator-protocol
cachePeriod: 1m
artifacts:
  - name: macos-amd64
    regexp: '^anon-live-macos-amd64.+'
  - name: macos-arm64
    regexp: '^anon-live-macos-arm64.+'
  - name: windows-amd64
    regexp: '^anon-live-windows-amd64.+'
  - name: debian-bullseye-amd64
    regexp: '^anon.+-live-.+bullseye.+amd64\.deb'
  - name: debian-bullseye-arm64
    regexp: '^anon.+-live-.+bullseye.+arm64\.deb'
  - name: debian-bookworm-amd64
    regexp: '^anon.+-live-.+bookworm.+amd64\.deb'
  - name: debian-bookworm-arm64
    regexp: '^anon.+-live-.+bookworm.+arm64\.deb'
  - name: ubuntu-focal-amd64
    regexp: '^anon.+-live-.+focal.+amd64\.deb'
  - name: ubuntu-focal-arm64
    regexp: '^anon.+-live-.+focal.+arm64\.deb'
  - name: ubuntu-jammy-amd64
    regexp: '^anon.+-live-.+jammy.+amd64\.deb'
  - name: ubuntu-jammy-arm64
    regexp: '^anon.+-live-.+jammy.+arm64\.deb'
